### ISSUE TITLE
회원 관련 API url 변경 제안 

### ISSUE THREAD

**Issue by busymidnight** [duck-map-project/duck-map-be#147]
## Description
> User -> Member renaming에 맞춰 회원 관련 API url 변경 제안

## To-do
- [ ] 회원가입 /members/join 
- [ ] 회원정보 수정, 조회, 탈퇴 /members/me OR /members/myinfo
- [ ] 비밀번호 변경 /members/me/password

## ETC
다른 의견도 좋습니다!

**Comment by busymidnight** [comment]
@LeeRim

**Comment by LeeRim** [comment]
> @LeeRim

@busymidnight  태그하기로 한거 까먹었어요ㅠㅠ 늦어서 죄송합니다..
