### ISSUE TITLE
이벤트 카테고리 repository 구현

### ISSUE THREAD

**Issue by LeeRim** [duck-map-project/duck-map-be#51]
## Description
> 이벤트 카테고리 repository 구현

## To-do
- [ ] 이벤트 카테고리 생성
- [ ] 이벤트 카테고리 전체 목록 조회
- [ ] 이벤트 카테고리 수정
- [ ] 이벤트 카테고리 삭제
